services:
  - type: web
    name: flask-backend
    env: python
    startCommand: gunicorn app:app
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    plan: free
    rootDir: python-model
